### ISSUE TITLE
怎么把数据显示到前台呢

### ISSUE THREAD

**Issue by 201505wuzixin** [xiaoshan5733/cms#2]
我下载了您的项目，实现了nodejs和数据库的交互，但是却不知道怎么把数据显示到前台。我是在做一个简易的app，用ionic写的，实在是想不出来，望解答！

**Comment by xiaoshan5733** [comment]
感谢关注，才发现我没写怎么访问前台页面 哈哈

1. 当应用启动之后可以通过 http://localhost:7000/ 访问前台页面
2. 首页前台代码路径  views/app/index.jade

如果还有不明白的可以给我发邮件 
谢谢

**Comment by xiaoshan5733** [comment]
@201505wuzixin 如果是通过其他应用访问本项目接口，可以参考routes/api/v1/下面的文件，比如http://localhost:7000/api/v1/content 对应内容列表，线上案例：https://wenglou.com/api/v1/content
